version: "3.8"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: reddit
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    depends_on:
      db:
        condition: service_healthy
    restart: always
    build: ./app
    command: sh -c "npm run server:start"
    init: true
    ports:
      - 3001:3001
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://postgres:reddit@db:5432/postgres
      - ARCH=x64
    stdin_open: true
    tty: true
    cap_add:
      - SYS_ADMIN
