FROM node:21

WORKDIR /usr/src/app
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true

RUN apt-get update
RUN apt-get install chromium -y
RUN apt-get install dumb-init

COPY --chown=node:node . .
RUN npm ci

USER node